version: '3.8'
services:
  web:
    # path to flask app (main folder where manage.py is located)
    build: ./
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./:/usr/src/app/
    ports:
      - 5000:5000
    # Environment variables for dev environment
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'flask_boilerplate_dev'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'flask_boilerplate_username'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'flask_boilerplate_password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'mysql_root_password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - mysql-db-data:/var/lib/mysql
volumes:
  mysql-db-data: